// Code generated by protoc-gen-go.
// source: github.com/sunfmin/myou/categories/proto/categories/main.proto
// DO NOT EDIT!

/*
Package myou_srv_categories is a generated protocol buffer package.

It is generated from these files:
	github.com/sunfmin/myou/categories/proto/categories/main.proto

It has these top-level messages:
	Project
	DeleteRequest
	Filter
	Input
	Category
	CategoryList
*/
package myou_srv_categories

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DeleteRequest struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Id      string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Filter struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Filter) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Input struct {
	Project  *Project  `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Category *Category `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
}

func (m *Input) Reset()                    { *m = Input{} }
func (m *Input) String() string            { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()               {}
func (*Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Input) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *Input) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type Category struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CategoryList struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *CategoryList) Reset()                    { *m = CategoryList{} }
func (m *CategoryList) String() string            { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()               {}
func (*CategoryList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "myou.srv.categories.Project")
	proto.RegisterType((*DeleteRequest)(nil), "myou.srv.categories.DeleteRequest")
	proto.RegisterType((*Filter)(nil), "myou.srv.categories.Filter")
	proto.RegisterType((*Input)(nil), "myou.srv.categories.Input")
	proto.RegisterType((*Category)(nil), "myou.srv.categories.Category")
	proto.RegisterType((*CategoryList)(nil), "myou.srv.categories.CategoryList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Categories service

type CategoriesClient interface {
	List(ctx context.Context, in *Filter, opts ...client.CallOption) (*CategoryList, error)
	Put(ctx context.Context, in *Input, opts ...client.CallOption) (*Category, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*Category, error)
}

type categoriesClient struct {
	c           client.Client
	serviceName string
}

func NewCategoriesClient(serviceName string, c client.Client) CategoriesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "myou.srv.categories"
	}
	return &categoriesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *categoriesClient) List(ctx context.Context, in *Filter, opts ...client.CallOption) (*CategoryList, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.List", in)
	out := new(CategoryList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesClient) Put(ctx context.Context, in *Input, opts ...client.CallOption) (*Category, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.Put", in)
	out := new(Category)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*Category, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.Delete", in)
	out := new(Category)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categories service

type CategoriesHandler interface {
	List(context.Context, *Filter, *CategoryList) error
	Put(context.Context, *Input, *Category) error
	Delete(context.Context, *DeleteRequest, *Category) error
}

func RegisterCategoriesHandler(s server.Server, hdlr CategoriesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Categories{hdlr}, opts...))
}

type Categories struct {
	CategoriesHandler
}

func (h *Categories) List(ctx context.Context, in *Filter, out *CategoryList) error {
	return h.CategoriesHandler.List(ctx, in, out)
}

func (h *Categories) Put(ctx context.Context, in *Input, out *Category) error {
	return h.CategoriesHandler.Put(ctx, in, out)
}

func (h *Categories) Delete(ctx context.Context, in *DeleteRequest, out *Category) error {
	return h.CategoriesHandler.Delete(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/sunfmin/myou/categories/proto/categories/main.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x36, 0xbb, 0xf9, 0xa6, 0x1e, 0xe2, 0x45, 0xab, 0x82, 0xf6, 0xe4, 0x29, 0x85,
	0x0a, 0x82, 0x07, 0x45, 0x98, 0x0c, 0x44, 0x85, 0x51, 0x04, 0xcf, 0x5d, 0x7d, 0xce, 0xc8, 0xda,
	0xd4, 0x34, 0x11, 0xe6, 0xd7, 0xf5, 0x8b, 0x58, 0xd3, 0xb4, 0x9b, 0x23, 0x6c, 0xb0, 0x5b, 0xf2,
	0xf2, 0x7b, 0xbf, 0x3c, 0xfe, 0x3c, 0xb8, 0x99, 0x30, 0xf9, 0xae, 0xc6, 0x34, 0xe1, 0x69, 0x50,
	0xa8, 0xec, 0x2d, 0x65, 0x59, 0x90, 0xce, 0xb8, 0x0a, 0x92, 0x58, 0xe2, 0x84, 0x0b, 0x86, 0x45,
	0x90, 0x0b, 0x2e, 0xf9, 0x62, 0x21, 0x8d, 0x59, 0x46, 0x75, 0x95, 0xec, 0xff, 0xc1, 0xb4, 0x10,
	0x5f, 0x74, 0xfe, 0xee, 0x1f, 0x42, 0x77, 0x24, 0xf8, 0x07, 0x26, 0x92, 0xec, 0x41, 0x8b, 0xbd,
	0x1e, 0x38, 0xa7, 0xce, 0xf9, 0x76, 0x54, 0x9e, 0xfc, 0x17, 0xd8, 0xbd, 0xc3, 0x29, 0x4a, 0x8c,
	0xf0, 0x53, 0x61, 0x21, 0xc9, 0x25, 0x74, 0xf3, 0x8a, 0xd5, 0x54, 0x3f, 0x3c, 0xa6, 0x16, 0x25,
	0x35, 0xbe, 0xa8, 0x86, 0x8d, 0xb8, 0xd5, 0x88, 0x9f, 0xc1, 0x1d, 0xb2, 0xa9, 0x44, 0xb1, 0xb1,
	0x91, 0x40, 0x27, 0x8b, 0x53, 0x34, 0x4e, 0x7d, 0xf6, 0xbf, 0x61, 0xeb, 0x3e, 0xcb, 0xd5, 0xe6,
	0x63, 0x5e, 0x41, 0xcf, 0x3c, 0xcf, 0xb4, 0xb8, 0x1f, 0x9e, 0x58, 0x1b, 0x07, 0x06, 0x8a, 0x1a,
	0xdc, 0xa7, 0xd0, 0xab, 0xab, 0xcb, 0x31, 0x5a, 0x67, 0x7d, 0x82, 0x9d, 0x9a, 0x7f, 0x64, 0x65,
	0xb2, 0xd7, 0x00, 0xf3, 0x0f, 0xca, 0xde, 0xf6, 0xfa, 0xcf, 0x17, 0x1a, 0xc2, 0x1f, 0x07, 0x60,
	0xd0, 0x5c, 0xc9, 0x10, 0x3a, 0xda, 0x7a, 0x64, 0x35, 0x54, 0xd1, 0x7b, 0x67, 0x2b, 0xf5, 0xba,
	0xff, 0x16, 0xda, 0xa3, 0x32, 0x4f, 0xcf, 0x4a, 0xea, 0xac, 0xbd, 0xd5, 0x43, 0x92, 0x07, 0x70,
	0xab, 0x15, 0x22, 0xbe, 0x15, 0xfc, 0xb7, 0x5f, 0x6b, 0x64, 0x63, 0x57, 0xaf, 0xf1, 0xc5, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x7e, 0x8a, 0x39, 0x08, 0x03, 0x00, 0x00,
}
